### ISSUE TITLE
Save and Install Service - System.ArgumentNullException: Value cannot be null.

### ISSUE THREAD

**Issue by laurinkeithdavis** [bloones/SyncThingWin#8]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Microsoft.Win32.RegistryKey.SetValue(String name, Object value, RegistryValueKind valueKind)
   at SyncThingTray.frmInstall.btnInstall_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

![capture](https://cloud.githubusercontent.com/assets/75857/7283016/3bdfc312-e8f9-11e4-8f2b-002651b10087.JPG)

**Comment by sirber** [comment]
same thing
